### ISSUE TITLE
Missing Instructions in the read.me

### ISSUE THREAD

**Issue by Shreyash0368** [Yash-Parsana/CrazyCoderWebApp#10]
## Missing Setup Instrucions

* npm install for the packages
* Setup of our own firebase account for the firebase config file
* How to create .env file for the firebaseconfig file env variables

I would like to fix these issues

**Comment by Yash-Parsana** [comment]
@Shreyash0368 this issue is assigned to you.

**Comment by Shreyash0368** [comment]
i was setting up the firebase env variable in my local but the firebaseconfig object given by firebase does not contain  measurement id and databse url, how do i get those?

**Comment by Shreyash0368** [comment]
Do we need the messenger id for the real time chat and the database URL to connect to the db that stores the info about contests? (im new to firebase so its my first time encountering these two)

**Comment by Yash-Parsana** [comment]
No Firebase database storing user data contest data comming from [CrazyCoderServerlessAPi](https://github.com/Yash-Parsana/CrazyCoderServerlessApi)

**Comment by Shreyash0368** [comment]
> No Firebase database storing user data contest data comming from [CrazyCoderServerlessAPi](https://github.com/Yash-Parsana/CrazyCoderServerlessApi)

Can u tell me how i can use the api, i have setup all other env variables except this one 

![image](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/114088740/ebf227e7-d29d-44e7-a21f-2482d471e1e5)

**Comment by adarsh1001111** [comment]
> > No Firebase database storing user data contest data comming from [CrazyCoderServerlessAPi](https://github.com/Yash-Parsana/CrazyCoderServerlessApi)
> 
> Can u please tell me how i can use the api, i have setup all other env variables except this one
> 
> ![image](https://private-user-images.githubusercontent.com/114088740/329824371-ebf227e7-d29d-44e7-a21f-2482d471e1e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzEwNTYsIm5iZiI6MTcxNTU3MDc1NiwicGF0aCI6Ii8xMTQwODg3NDAvMzI5ODI0MzcxLWViZjIyN2U3LWQyOWQtNDRlNy1hMjFmLTI0ODJkNDcxZTFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwMzI1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmMyYTlmNzVjN2Q4ZGI3ZjgzYzNjZjcxOTg2NTgwODFhNTVkZDU4MTU1ZjlhMWQwNGZiOTA1OTkzYWRmOTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lCRV8t-VgtHNl4V0vkSN6EwdyO1BSPu0heZbA1LjTao)

can you elaborate to me what issue are you facing exactly , is the page loading or firebase issue , please provide the error SS as well

**Comment by Yash-Parsana** [comment]
I have added test.env file for firabase test environment. it also need some initial database setup from firebase side so i have done it.
