### ISSUE TITLE
Adding Recommendations of contests features by asking details about user

### ISSUE THREAD

**Issue by Chelseasingla1** [Yash-Parsana/CrazyCoderWebApp#12]
I would like to add a recommendation feature where app would give recommendations to user by itself to join contests based on user profile description like what are they studying right now or their interests.
Please assign me this issue under GSSoC'24

**Comment by Yash-Parsana** [comment]
@Chelseasingla1 thank you for suggest this feature but i don't think it is required.

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 thank you for suggesting this feature but i don't think it is required.

@Yash-Parsana Okay
