### ISSUE TITLE
[feature] Add Coding Ninjas Section

### ISSUE THREAD

**Issue by PilotAxis** [Yash-Parsana/CrazyCoderWebApp#16]
Hey, @Yash-Parsana I would like to add the following feature of Coding Ninjas that will include a section of upcoming and present contests going on Coding Ninjas platforms, I would request you to assign me this issue to add this feature for the project. Mention the level that is required to assign the issue.

**Comment by Yash-Parsana** [comment]
@PilotAxis How you will get coding ninjas contest data?

**Comment by Yash-Parsana** [comment]
this issue should be raised in this repo [CrazyCoderServerlessApi](https://github.com/Yash-Parsana/CrazyCoderServerlessApi).
