### ISSUE TITLE
Adding the hover effects on buttons

### ISSUE THREAD

**Issue by anshulsoni4** [Yash-Parsana/CrazyCoderWebApp#17]

**Comment by manvichaudhary55** [comment]
I can add the hover effects to the button . Please assign this issue to me under Gssoc'24

**Comment by aamna111** [comment]
i can add hover effects on buttons . pls assign this issue to me under Gssoc'24.

**Comment by Yash-Parsana** [comment]
@anshulsoni4 please describe issue properly with screenshots and what you want to implement while raising new issue.
otherwise it will be closed without any comments.
