### ISSUE TITLE
Spacing in the dashboard and the headers 

### ISSUE THREAD

**Issue by anshulsoni4** [Yash-Parsana/CrazyCoderWebApp#20]
![image](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/74638335/07892484-aa2e-46ee-9590-c70423402a32)

**Comment by Ansh101112** [comment]
please assign me this issue @Yash-Parsana @anshulsoni4

**Comment by Yash-Parsana** [comment]
@anshulsoni4 what you want to solve ?

**Comment by anshulsoni4** [comment]
> @anshulsoni4 what you want to solve ?

the spacing from horizontal and vertical (inside the elements that is buttons)

**Comment by Yash-Parsana** [comment]
@anshulsoni4 Are you talking about horizontal and vertical spacing inside atcoder,codechef,... buttons right?

**Comment by anshulsoni4** [comment]
> @anshulsoni4 Are you talking about horizontal and vertical spacing inside atcoder,codechef,... buttons right?

outside of them as well

**Comment by Yash-Parsana** [comment]
@anshulsoni4 i think it looks good. you may find ui enhancement issues in small screen size (mobile size). if you find any then raise it.
