### ISSUE TITLE
[file missing] We need '.env*' 

### ISSUE THREAD

**Issue by MishraTanishq619** [Yash-Parsana/CrazyCoderWebApp#23]
While we run development server, some environment variables are required.
They are imported at various places.

We need a '.env.example' file to guide one to start development server.
(must be done by maintainer specefically)

- [x] We need a '.env.example' file.
- [x] Update ReadMe for App Starting instructions.

**Comment by MishraTanishq619** [comment]
@Yash-Parsana , Please Help this out.

**Comment by Yash-Parsana** [comment]
@MishraTanishq619 Now I have added test.env file.
