### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Yash-Parsana/CrazyCoderWebApp#27]
## Security Feature
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.
Assign me this work under GSSoC24, I will implement it.

**Comment by Yash-Parsana** [comment]
@pankaj-bind I am intentionally allowing that kind of email in webapp. In crazycoderApp you can not enter in app without email verification.
