### ISSUE TITLE
[Bug] : Button are not accessable

### ISSUE THREAD

**Issue by sivaprasath2004** [Yash-Parsana/CrazyCoderWebApp#28]
- In the button has hovered cannot be the cursor `pointing` this is `text point`...
- Because the user can be hover that is not `clickable` link 
- This is irresponsive .so please assign me to redy to solve this.... :eyes: 
![Screenshot from 2024-05-13 21-58-19](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/121082414/9a0cc638-4786-4cfc-9ae6-d01747e0958c)

**Comment by Yash-Parsana** [comment]
@sivaprasath2004 i don't undestand what are you talking about. but i checked this component it is working properly.
