### ISSUE TITLE
Missing back to home in Chat page

### ISSUE THREAD

**Issue by NitinChakrawarti** [Yash-Parsana/CrazyCoderWebApp#30]
In chat page back to home button is missing, which makes user experience horrible.
I want to work on this issue under GSSoC'24.
Please assign this issue to me @Yash-Parsana .

https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/149225785/0a6256ba-e23a-43a1-b8a7-60655c89c152

**Comment by Yash-Parsana** [comment]
duplicate issue #14 .
