### ISSUE TITLE
Light mode version 

### ISSUE THREAD

**Issue by NitinChakrawarti** [Yash-Parsana/CrazyCoderWebApp#31]
in website i there is no button to switch between light and dark mode, 

i can create a button to switch between light and dark mode and also make it functional by applying  different CSS to light mode.

@Yash-Parsana  please assign this issue to me i want to contribute in this project under GSSoC'24.

![Screenshot 2024-05-15 124930](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/149225785/372cfcad-3ebb-4e00-a789-ea0968c78edf)

**Comment by Yash-Parsana** [comment]
@NitinChakrawarti This issue is assigned to you.

Acceptance criteria:
- Light/dark mode should work accross all pages.
- Ui should look good in light mode.
- record video of changes and post with PR.

**Comment by NitinChakrawarti** [comment]
> @NitinChakrawarti This issue is assigned to you.
> 
> Acceptance criteria:
> 
> * Light/dark mode should work accross all pages.
> * Ui should look good in light mode.
> * record video of changes and post with PR.
> 
> I have added firebaseConfig in readme.md use that to test Leaderboard , chat and profile section.

okay for sure.

**Comment by NitinChakrawarti** [comment]
@Yash-Parsana sir i will be good if I add shade of white in background and fonts colors to shade of something dark blue ?

**Comment by Yash-Parsana** [comment]
@NitinChakrawarti How it is going ?

**Comment by drick-infinity** [comment]
I want to contribute assign this task to me under gssoc'24
As i learned MERN  full stack development

**Comment by me-nilakshi** [comment]
This task has been pending over 20 days. Assign this to me @Yash-Parsana , I'll complete it within 2 days.
