### ISSUE TITLE
Add more info in footer

### ISSUE THREAD

**Issue by YadlaMani** [Yash-Parsana/CrazyCoderWebApp#32]
Improving navbar and fixing the spacing and adding more info if suggested
![image](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/133841094/510bffd5-be93-449a-ad97-90075936d3d9)

**Comment by YadlaMani** [comment]
@Yash-Parsana pls assign me this issue under gssoc'24

**Comment by Yash-Parsana** [comment]
it is duplicate of #25. please add comment there if issue creator is not ready to work then it will be assigned to you.
