### ISSUE TITLE
Bug: In the mobile view content of the navbar or sidebar toggler display behind the login page

### ISSUE THREAD

**Issue by AbhiDiva96** [Yash-Parsana/CrazyCoderWebApp#40]
## In the mobile view content of the navbar or sidebar toggler display behind the login page

pls assigned me under the gssoc'24
@Yash-Parsana 

![Screenshot 2024-05-17 165048](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/112077897/a756a73f-345a-4b64-8411-af4890ffeffd)

## all sidebar toggler content should be upside of the login page

![Screenshot 2024-05-17 165036](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/112077897/3882ae6f-0527-46dd-a1c6-a16ae7a546b2)

**Comment by Yash-Parsana** [comment]
@AbhiDiva96 This issue is assigned to you.

Provide screen recording with PR.

**Comment by AbhiDiva96** [comment]
Ok I will soon create a PR
@Yash-Parsana

**Comment by AbhiDiva96** [comment]
hey @Yash-Parsana 
I have fixed the issue pls review and merge it.
