### ISSUE TITLE
Bug: Signup button not working

### ISSUE THREAD

**Issue by AbhiDiva96** [Yash-Parsana/CrazyCoderWebApp#41]
## On clicking the signup/login button it redirected to only the login page. login and signup both buttons would be in the two different div. so that users can easily access the signup and login page

Please assign me under the gssoc'24
@Yash-Parsana 

## Signup and login button would be two different div
![Screenshot 2024-05-17 165800](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/112077897/0f878067-23fc-46fa-9196-64b16aaf38a1)

## Opening direct login page, not signup
![Screenshot 2024-05-17 165808](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/112077897/06a9f40d-cc89-4675-84ee-1382cd7b7f81)

**Comment by Yash-Parsana** [comment]
You may find signUp option in bottom of login popup.

**Comment by AbhiDiva96** [comment]
But one signup button should be at navbar so that the user can create an account easily 
@Yash-Parsana
