### ISSUE TITLE
Fix sign in and login page

### ISSUE THREAD

**Issue by GOURAVSINGH19** [Yash-Parsana/CrazyCoderWebApp#58]
![Screenshot 2024-05-22 233017](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/120244528/0648ce4b-1059-4ba8-88b2-37da0e7b001b)
As you can see menu and sign page is not looking good ...
If you think it is good issue then assign me,...
@Yash-Parsana

**Comment by Yash-Parsana** [comment]
duplicate #40
