### ISSUE TITLE
💡[FEATURE]: 404 page not found page devlop

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Yash-Parsana/CrazyCoderWebApp#65]
**Is your feature request related to a problem? Please describe.**
💡[FEATURE]: 404 page not found page devlop

**Describe the solution you'd like**
there is no 404 not found page in your website
**Describe alternatives you've considered**

**Additional context**

**Comment by Shubham-Zone** [comment]
@Yash-Parsana please assign this to me i am GSSOC'24 contributor and have 2+ years of exp in development
