### ISSUE TITLE
💡[FEATURE]: Add some hover effect on navbar links

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Yash-Parsana/CrazyCoderWebApp#66]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/125277258/e42411c2-b5a4-42c6-8e31-bb911e9c7989)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by keerthinannepamula1** [comment]
May I work on this issue?

**Comment by Shubham-Zone** [comment]
@Yash-Parsana please assign this to me i am GSSOC'24 contributor and have 2+ years of exp in development
