### ISSUE TITLE
[Bug]The Confirm Password field in SignUp Form 

### ISSUE THREAD

**Issue by Disha-Hati** [Yash-Parsana/CrazyCoderWebApp#7]
The Confirm Password field in SignUp Form doesn't have the password property, we can see the password as we type. 

I am GSSOC'24 Contributor, @Yash-Parsana Can you please assign this issue to me?

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by Yash-Parsana** [comment]
It is expected behaviour @Disha-Hati.
